chore(ci): keep layer version, trigger only after success

diff --git a/.github/workflows/publish_layer.yml b/.github/workflows/publish_layer.yml
--- a/.github/workflows/publish_layer.yml
+++ b/.github/workflows/publish_layer.yml
@@ -18,8 +18,22 @@ on:
 
 
 jobs:
+  on-success:
+    runs-on: ubuntu-latest
+    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
+    steps:
+      - run: echo 'The triggering workflow passed, continue'
+
+  on-failure:
+    runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+    steps:
+      - run: echo 'The triggering workflow failed, aborting'
+
+
   build-layer:
     runs-on: ubuntu-latest
+    needs: on-success
     defaults:
       run:
         working-directory: ./layer
@@ -38,8 +52,8 @@ jobs:
       - name: Set release notes tag
         run: |
           RELEASE_INPUT=${{ inputs.latest_published_version }}
-          GITHUB_EVENT_RELEASE_TAG=${{ github.event.release.tag_name }}
-          RELEASE_TAG_VERSION=${GITHUB_EVENT_RELEASE_TAG:-$RELEASE_INPUT}
+          LATEST_TAG=$(git describe --tag --abbrev=0)
+          RELEASE_TAG_VERSION=${RELEASE_INPUT:-$LATEST_TAG}
           echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION:1}" >> $GITHUB_ENV
       - name: install cdk and deps
         run: |
